// autogenerated file, do not edit

#pragma once

namespace pose_inference{

constexpr std::string_view CONFIG_DIR = "/home/docker/workspace/build/dependencies/Docker-OpenCV-TensorRT-Dev/modules/pose_inference/cfg";
constexpr uint16_t BATCH_SIZE = 5;

} // namespace pose_inference
