// autogenerated file, do not edit

#pragma once

namespace pose_inference{

constexpr std::string_view CONFIG_DIR = "/home/docker/workspace/modules/pose-inference/cfg";
constexpr uint16_t BATCH_SIZE = 5;

} // namespace pose_inference
